-- 코드를 입력하세요
SELECT
    a.PRODUCT_CODE,
    (a.PRICE*sum(b.SALES_AMOUNT)) as SALES
FROM PRODUCT as a
INNER JOIN OFFLINE_SALE as b
    on a.PRODUCT_ID=b.PRODUCT_ID
GROUP BY b.PRODUCT_ID
ORDER BY SALES DESC,a.PRODUCT_CODE