-- 코드를 입력하세요
SELECT
    b.INGREDIENT_TYPE as INGREDIENT_TYPE,
    sum(a.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as a
INNER JOIN ICECREAM_INFO as b
    on a.FLAVOR=b.FLAVOR
GROUP BY INGREDIENT_TYPE
